name: Deploy to GitHub Pages

# 每次程式碼Push到master，執行workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # 使用ubuntu
    runs-on: ubuntu-latest
    steps:
    # 使用checkout actions
    - uses: actions/checkout@v2
    
    # 安裝.NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 3.1    
       
    # 發佈程式到Release資料夾
    - name: Publish .NET Core Project
      run: dotnet publish AboutMe.csproj -c Release -o release --nologo
    
    # 加入一個.nojekyll檔案
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    # 將release/wwwroot的程式碼，push到gh-pages分支
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUBPAGE }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
